'''
Compares two ways of integrating a noisy IMU (gyro + body-frame velocity) stream
into a pose estimate:

  1. "naive" - orientation kept as a 3-vector of Euler angles (roll, pitch, yaw),
     updated by directly adding the measured body angular rate: euler += omega*dt.
     This treats SO(3) as if it were a flat vector space, which is only valid to
     first order and breaks down as soon as the attitude has any appreciable
     rotation (it ignores the nonlinear Euler-rate kinematic transform).

  2. "expmap" - orientation kept as a rotation matrix, updated on the SO(3)
     manifold itself: R *= Exp(omega*dt), using the closed-form Rodrigues formula.

Both estimators consume the *same* noisy measurements each step, so any gap
between them isolates the error introduced by the naive vector-space
approximation itself (on top of the noise both share), rather than being an
artifact of different noise draws.

Ground truth is generated by exp-map-integrating the noise-free rates, which is
exact under the zero-order-hold assumption of constant rate within each dt.
'''

import argparse

import numpy as np
import matplotlib.pyplot as plt


def skew(v):
    return np.array([
        [0, -v[2], v[1]],
        [v[2], 0, -v[0]],
        [-v[1], v[0], 0],
    ])


def so3_exp(omega):
    """Rodrigues' formula: exact exponential map for a constant body rate over dt."""
    theta = np.linalg.norm(omega)
    if theta < 1e-8:
        return np.eye(3) + skew(omega)
    axis_skew = skew(omega / theta)
    return (np.eye(3)
            + np.sin(theta) * axis_skew
            + (1 - np.cos(theta)) * (axis_skew @ axis_skew))


def euler_to_R(rpy):
    """ZYX (roll-pitch-yaw) Euler angles to rotation matrix."""
    roll, pitch, yaw = rpy
    cr, sr = np.cos(roll), np.sin(roll)
    cp, sp = np.cos(pitch), np.sin(pitch)
    cy, sy = np.cos(yaw), np.sin(yaw)
    Rx = np.array([[1, 0, 0], [0, cr, -sr], [0, sr, cr]])
    Ry = np.array([[cp, 0, sp], [0, 1, 0], [-sp, 0, cp]])
    Rz = np.array([[cy, -sy, 0], [sy, cy, 0], [0, 0, 1]])
    return Rz @ Ry @ Rx


def rotation_geodesic_error(R_a, R_b):
    """Angle (rad) of the relative rotation between two rotation matrices."""
    c = (np.trace(R_a.T @ R_b) - 1.0) / 2.0
    return np.arccos(np.clip(c, -1.0, 1.0))


def true_body_rates(t):
    """Smooth, persistently-exciting angular & linear body-frame rate profile."""
    omega = np.array([
        0.6 * np.sin(0.7 * t),
        0.5 * np.cos(0.4 * t + 0.3),
        0.8 * np.sin(0.25 * t + 1.0),
    ])
    v = np.array([
        1.0 * np.cos(0.3 * t),
        0.5 * np.sin(0.2 * t),
        0.2 * np.sin(0.5 * t),
    ])
    return omega, v


def run_simulation(duration, dt, gyro_noise_std, vel_noise_std, seed):
    rng = np.random.default_rng(seed)
    n_steps = int(duration / dt)

    R_true, p_true = np.eye(3), np.zeros(3)
    R_naive_euler = np.zeros(3)   # naive estimator's own attitude state (roll,pitch,yaw)
    R_naive, p_naive = np.eye(3), np.zeros(3)
    R_exp, p_exp = np.eye(3), np.zeros(3)

    t_hist = np.zeros(n_steps)
    rot_err_naive = np.zeros(n_steps)
    rot_err_exp = np.zeros(n_steps)
    pos_err_naive = np.zeros(n_steps)
    pos_err_exp = np.zeros(n_steps)

    for k in range(n_steps):
        t = k * dt
        omega_true, v_true = true_body_rates(t)

        # Ground truth: exact SO(3) integration of the noise-free rates.
        R_true = R_true @ so3_exp(omega_true * dt)
        p_true = p_true + R_true @ v_true * dt

        # Shared noisy IMU measurement.
        omega_meas = omega_true + rng.normal(0.0, gyro_noise_std, 3)
        v_meas = v_true + rng.normal(0.0, vel_noise_std, 3)

        # Naive: Euler angles treated as a flat vector space.
        R_naive_euler = R_naive_euler + omega_meas * dt
        R_naive = euler_to_R(R_naive_euler)
        p_naive = p_naive + R_naive @ v_meas * dt

        # Exp-map: proper SO(3) manifold update.
        R_exp = R_exp @ so3_exp(omega_meas * dt)
        p_exp = p_exp + R_exp @ v_meas * dt

        t_hist[k] = t
        rot_err_naive[k] = np.degrees(rotation_geodesic_error(R_true, R_naive))
        rot_err_exp[k] = np.degrees(rotation_geodesic_error(R_true, R_exp))
        pos_err_naive[k] = np.linalg.norm(p_true - p_naive)
        pos_err_exp[k] = np.linalg.norm(p_true - p_exp)

    return t_hist, rot_err_naive, rot_err_exp, pos_err_naive, pos_err_exp


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--duration", type=float, default=20.0, help="Simulation length in seconds")
    parser.add_argument("--dt", type=float, default=0.005, help="IMU sample interval in seconds")
    parser.add_argument("--gyro-noise-std", type=float, default=0.02, help="Gyro noise std-dev (rad/s)")
    parser.add_argument("--vel-noise-std", type=float, default=0.05, help="Body-velocity noise std-dev (m/s)")
    parser.add_argument("--seed", type=int, default=0, help="RNG seed")
    parser.add_argument("--out", type=str, default=None, help="Save the figure to this path instead of showing it")
    args = parser.parse_args()

    t, rot_err_naive, rot_err_exp, pos_err_naive, pos_err_exp = run_simulation(
        args.duration, args.dt, args.gyro_noise_std, args.vel_noise_std, args.seed,
    )

    fig, (ax_rot, ax_pos) = plt.subplots(2, 1, figsize=(9, 7), sharex=True)

    ax_rot.plot(t, rot_err_naive, label="naive (Euler-angle, vector-space)", color="tab:red")
    ax_rot.plot(t, rot_err_exp, label="Exp-map (SO(3))", color="tab:blue")
    ax_rot.set_ylabel("Rotation error (deg)")
    ax_rot.set_yscale("log")
    ax_rot.legend()
    ax_rot.set_title("Attitude error: naive Euler-angle vs. SO(3) Exp-map integration")

    ax_pos.plot(t, pos_err_naive, label="naive (Euler-angle, vector-space)", color="tab:red")
    ax_pos.plot(t, pos_err_exp, label="Exp-map (SE(3))", color="tab:blue")
    ax_pos.set_ylabel("Position error (m)")
    ax_pos.set_xlabel("Time (s)")
    ax_pos.set_yscale("log")
    ax_pos.legend()

    fig.tight_layout()
    if args.out:
        fig.savefig(args.out, dpi=150)
        print(f"Saved figure to {args.out}")
    else:
        plt.show()


if __name__ == "__main__":
    main()
