[project]
name = "python-codebase"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "opencv-python",
    "scikit-learn",
    "scipy",
    "matplotlib",
    "manifpy",
]

[tool.uv.sources]
manifpy = { path = "../manif" }
